(function(){
  let lastSignature='';
  const getCollab=()=>{let c=JSON.parse(localStorage.getItem('erp-ai-collab')||'{}');if(!c.projectId){c.projectId='project-'+Date.now();localStorage.setItem('erp-ai-collab',JSON.stringify(c))}return c};
  const getHistory=()=>JSON.parse(localStorage.getItem('erp-ai-project-history')||'[]');
  const toChinese=n=>['一','二','三','四','五','六','七','八','九','十'][n-1]||n;
  function currentProject(c,index){if(!c.requirement&&!c.implementation&&!c.code)return null;let scene=(c.privateNotes||[]).find(n=>n.role==='customer')?.text||c.requirement?.title||'未命名项目';return{id:c.projectId||'current',name:`项目${toChinese(index+1)}`,scene:scene.slice(0,28),requirement:c.requirement||null,implementation:c.implementation||null,code:c.code||null,current:true}}
  function projects(){let history=getHistory(),cur=currentProject(getCollab(),history.length);return cur?[...history,cur]:history}
  function syncRelations(items){if(typeof state==='undefined')return;items.forEach((p,i)=>{let r=state.requirements.find(r=>r.projectId===p.id);if(p.requirement&&!r){state.requirements.unshift({id:'req-'+p.id,projectId:p.id,code:'REQ-PROJECT-'+String(i+1).padStart(3,'0'),name:p.scene||p.name,org:'',dept:'',priority:'中',file:'三方协作需求方案',status:p.code?'已完成':p.implementation?'已确认':'待确认',time:p.requirement.time||new Date().toLocaleString(),progress:p.code?4:0})}else if(r)r.status=p.code?'已完成':p.implementation?'已确认':'待确认';if(p.code&&!state.apps.some(a=>a.projectId===p.id))state.apps.push({id:'app-'+p.id,projectId:p.id,name:p.scene||p.name,org:'',version:'1.0.0'})});localStorage.setItem('erp-ai-demo',JSON.stringify(state))}
  function renderPanel(){let panel=document.querySelector('#assistant .delivery-panel');if(!panel)return;let items=projects();syncRelations(items);let sig=JSON.stringify(items.map(p=>[p.id,!!p.requirement,!!p.implementation,!!p.code]));if(sig===lastSignature&&panel.dataset.simpleProjects==='1')return;lastSignature=sig;panel.dataset.simpleProjects='1';panel.innerHTML=`<div class="project-panel-head"><div><h3>项目</h3><span>点击项目查看交付内容</span></div><button class="project-add" data-project-action="new">＋</button></div><div class="project-list">${items.length?items.map((p,i)=>`<button class="project-row" data-project-id="${p.id}"><span class="project-number">${i+1}</span><span><b>${p.name}</b><small>${p.scene}</small></span><em>${[p.requirement,p.implementation,p.code].filter(Boolean).length}/3</em></button>`).join(''):'<div class="project-empty"><b>暂无项目</b><span>发送第一份需求方案后，项目会出现在这里。</span></div>'}</div>`}
  function artifact(title,item,target){return `<article class="project-artifact ${item?'ready':''}"><i>${item?'✓':'○'}</i><div><b>${title}</b><span>${item?'已交付':'尚未交付'}</span></div>${item?`<button class="secondary" data-project-view="${title}">查看</button>`:''}<button class="link" data-project-go="${target}">前往关联模块 →</button></article>`}
  function openProject(id){let p=projects().find(x=>x.id===id);if(!p)return;modal(`<div class="modal-head"><div><h2>${p.name}</h2><p>${p.scene}</p></div><button data-close>×</button></div><div class="project-artifacts">${artifact('需求',p.requirement,'requirements')}${artifact('实施文档',p.implementation,'generation')}${artifact('开发代码',p.code,'apps')}</div><div class="relation-note"><b>项目关联</b><p>需求同步到“需求中心”，实施进度关联“项目进度”，代码交付同步到“应用中心”。</p></div><div class="modal-actions"><button class="secondary" data-close>关闭</button></div>`)}
  function newProject(){let c=getCollab();if(c.requirement||c.implementation||c.code){let history=getHistory(),archived=currentProject(c,history.length);archived.current=false;history.push(archived);localStorage.setItem('erp-ai-project-history',JSON.stringify(history))}localStorage.setItem('erp-ai-collab',JSON.stringify({role:c.role||'customer',projectId:'project-'+(Date.now()+1),privateNotes:[],questionnaire:null,requirement:null,implementation:null,code:null}));location.reload()}
  document.addEventListener('click',e=>{let row=e.target.closest('[data-project-id]');if(row){openProject(row.dataset.projectId);return}let action=e.target.closest('[data-project-action]');if(action?.dataset.projectAction==='new'){newProject();return}let go=e.target.closest('[data-project-go]');if(go){closeModal();showView(go.dataset.projectGo);return}let view=e.target.closest('[data-project-view]');if(view)toast(`${view.dataset.projectView}已打开（演示）`)});
  setInterval(renderPanel,700);renderPanel();
})();
