(function(){
  let lastSignature='';
  const getCollab=()=>{let c=JSON.parse(localStorage.getItem('erp-ai-collab')||'{}');if(!c.projectId){c.projectId='project-'+Date.now();localStorage.setItem('erp-ai-collab',JSON.stringify(c))}return c};
  const getHistory=()=>JSON.parse(localStorage.getItem('erp-ai-project-history')||'[]');
  const toChinese=n=>['一','二','三','四','五','六','七','八','九','十'][n-1]||n;
  function currentProject(c,index){if(!c.requirement&&!c.implementation&&!c.code&&!c.questionnaire&&!(c.privateNotes||[]).length)return null;let scene=(c.privateNotes||[]).find(n=>n.role==='customer')?.text||c.requirement?.title||'未命名项目';return{id:c.projectId||'current',name:c.projectMeta?.name||`项目${toChinese(index+1)}`,scene:scene.slice(0,28),projectMeta:c.projectMeta||{},requirement:c.requirement||null,implementation:c.implementation||null,code:c.code||null,acceptance:c.acceptance||null,events:c.events||[],current:true}}
  function projects(){let history=getHistory(),cur=currentProject(getCollab(),history.length);return cur?[...history,cur]:history}
  function syncRelations(items){if(typeof state==='undefined')return;items.forEach((p,i)=>{const accepted=p.acceptance?.status==='accepted',rejected=p.acceptance?.status==='rejected',projectStatus=accepted?'已完成':p.code?'待验收':p.implementation?'已确认':'待确认',projectProgress=accepted?4:p.code?3:p.implementation?2:p.requirement?1:0;let r=state.requirements.find(r=>r.projectId===p.id),related={implementationFile:p.implementation?.file?.name||'',implementationFileMeta:p.implementation?.file||null,deliveryFile:p.code?.file?.name||'',deliveryFileMeta:p.code?.file||null,acceptance:p.acceptance||null,projectMeta:p.projectMeta||{}};if(p.requirement&&!r){state.requirements.unshift({id:'req-'+p.id,projectId:p.id,code:'REQ-PROJECT-'+String(i+1).padStart(3,'0'),name:p.projectMeta?.name||p.scene||p.name,org:p.projectMeta?.organization||'',dept:p.projectMeta?.department||'',priority:'中',file:p.requirement.file?.name||'AI结构化需求方案',status:projectStatus,time:p.requirement.time||new Date().toLocaleString(),progress:projectProgress,...related})}else if(r){r.name=p.projectMeta?.name||r.name;r.org=p.projectMeta?.organization||r.org;r.dept=p.projectMeta?.department||r.dept;r.status=projectStatus;r.progress=projectProgress;Object.assign(r,related)}let app=state.apps.find(a=>a.projectId===p.id);if(accepted&&!app){state.apps.push({id:'app-'+p.id,projectId:p.id,name:p.projectMeta?.name||p.scene||p.name,org:p.projectMeta?.organization||'',version:p.code.version||'1.0.0',status:'已验收',deliveryFile:p.code.file?.name||'',deliveryFileMeta:p.code.file||null,implementationFile:p.implementation?.file?.name||'',implementationFileMeta:p.implementation?.file||null,requirementTitle:p.requirement?.title||''})}else if(app){app.version=p.code?.version||app.version;app.status=accepted?'已验收':rejected?'已退回':'待验收';app.deliveryFile=p.code?.file?.name||app.deliveryFile;app.deliveryFileMeta=p.code?.file||app.deliveryFileMeta;app.implementationFile=p.implementation?.file?.name||app.implementationFile;app.implementationFileMeta=p.implementation?.file||app.implementationFileMeta}});localStorage.setItem('erp-ai-demo',JSON.stringify(state))}
  function renderPanel(){let panel=document.querySelector('#assistant .delivery-panel');if(!panel)return;let items=projects();syncRelations(items);let sig=JSON.stringify(items.map(p=>[p.id,p.name,!!p.requirement,!!p.implementation,!!p.code,p.acceptance?.status||'']));if(sig===lastSignature&&panel.dataset.simpleProjects==='1')return;lastSignature=sig;panel.dataset.simpleProjects='1';panel.innerHTML=`<div class="project-panel-head"><div><h3>项目</h3><span>点击项目查看交付内容</span></div><button class="project-add" data-project-action="new">＋</button></div><div class="project-list">${items.length?items.map((p,i)=>`<button class="project-row" data-project-id="${p.id}"><span class="project-number">${i+1}</span><span><b>${p.name}</b><small>${p.scene}</small></span><em>${[p.requirement,p.implementation,p.code].filter(Boolean).length}/3</em></button>`).join(''):'<div class="project-empty"><b>暂无项目</b><span>发送第一份需求方案后，项目会出现在这里。</span></div>'}</div>`}
  function artifact(title,item,target){return `<article class="project-artifact ${item?'ready':''}"><i>${item?'✓':'○'}</i><div><b>${title}</b><span>${item?'已交付':'尚未交付'}</span></div>${item?`<button class="secondary" data-project-view="${title}">查看</button>`:''}<button class="link" data-project-go="${target}">前往关联模块 →</button></article>`}
  function archivedAcceptance(p){const ready=[p.requirement,p.implementation,p.code].filter(Boolean).length;return `<div class="archived-acceptance"><div><b>交付资料</b><span>${ready}/3 项已提交</span></div><div class="project-artifacts">${artifact('需求',p.requirement,'requirements')}${artifact('实施文档',p.implementation,'generation')}${artifact('开发代码',p.code,'apps')}</div><div class="acceptance-result"><b>${p.acceptance?.status==='accepted'?'验收通过':p.acceptance?.status==='rejected'?'已驳回修改':'等待客户验收'}</b><span>${p.acceptance?.time||''}</span></div></div>`}
  function openProject(id){
    const p=projects().find(x=>x.id===id);if(!p)return;
    const meta=p.projectMeta||{};
    const acceptance=p.current&&typeof window.renderCurrentAcceptance==='function'?window.renderCurrentAcceptance():archivedAcceptance(p);
    modal(`<div class="project-detail-modal"><div class="modal-head"><div><h2>${p.name}</h2><p>${p.scene}</p></div><button data-close>×</button></div><div class="project-detail-meta"><span><small>客户组织</small><b>${meta.organization||'未填写'}</b></span><span><small>所属部门</small><b>${meta.department||'未填写'}</b></span><span><small>项目负责人</small><b>${meta.owner||'未填写'}</b></span><span><small>当前状态</small><b>${p.acceptance?.status==='accepted'?'已验收':p.acceptance?.status==='rejected'?'已驳回':p.code?'待验收':p.implementation?'开发中':'需求确认'}</b></span></div>${acceptance}<div class="relation-note"><b>资料关联</b><p>需求来自“需求中心”，实施文档和代码由项目成员提交，客户验收通过后自动归档到“应用中心”。</p></div><div class="modal-actions"><button class="secondary" data-close>关闭</button></div></div>`)
  }
  function newProject(){let c=getCollab();if(c.requirement||c.implementation||c.code||c.questionnaire||(c.privateNotes||[]).length){let history=getHistory(),archived=currentProject(c,history.length);archived.current=false;history.push(archived);localStorage.setItem('erp-ai-project-history',JSON.stringify(history))}localStorage.setItem('erp-ai-collab',JSON.stringify({role:c.role||'customer',projectId:'project-'+(Date.now()+1),projectMeta:{name:'',organization:'',department:'',owner:'',planDate:''},privateNotes:[],questionnaire:null,pendingIntent:null,requirement:null,implementation:null,implementationVersions:[],code:null,codeVersions:[],acceptance:null,events:[]}));location.reload()}
  document.addEventListener('click',e=>{let row=e.target.closest('[data-project-id]');if(row){openProject(row.dataset.projectId);return}let action=e.target.closest('[data-project-action]');if(action?.dataset.projectAction==='new'){newProject();return}let go=e.target.closest('[data-project-go]');if(go){closeModal();showView(go.dataset.projectGo);return}let view=e.target.closest('[data-project-view]');if(view)toast(`${view.dataset.projectView}已打开（演示）`)});
  window.startNewProject=newProject;setInterval(renderPanel,700);renderPanel();
})();
